import type { BrandVariants } from '@fluentui/react-components';

/**
 * The handbook's four brand colours.
 *
 * - `crimson` is the primary: links, active navigation, focus, filled buttons.
 * - `plum` is the dark-mode page surface; every other dark neutral is tinted
 *   towards it (see `tintNeutrals`).
 * - `white` is the light-mode page surface, which is also Fluent's default.
 * - `amber` is a secondary accent. It only ever appears as a *fill* carrying
 *   `amberInk` text: amber on white is 1.66:1, far below AA, so it can never be
 *   used as text or as a border on a light surface.
 */
export const palette = {
  crimson: '#ca1f3d',
  amber: '#ffbe00',
  amberInk: '#25182e',
  white: '#ffffff',
  plum: '#25182e',
} as const;

/**
 * Fluent's 16-step brand ramp, in crimson.
 *
 * Generated by taking `brandWeb`'s lightness and chroma curve in OKLCh —
 * Microsoft's ramp is tuned so each theme's derived tokens land at usable
 * contrast — and re-hue'ing it to `palette.crimson`, which is pinned at step 80
 * (the step Fluent uses for `colorBrandBackground` and light-mode
 * `colorBrandForeground1`). Out-of-gamut steps had their chroma reduced until
 * they fit sRGB.
 *
 * The resulting contrast against the page surfaces, all AA or better:
 * crimson text on white 5.56:1, white on crimson 5.56:1, and step 100
 * (dark-mode `colorBrandForeground1`) on plum 5.43:1.
 */
export const crimsonRamp: BrandVariants = {
  10: '#270b0d',
  20: '#3c1013',
  30: '#4f141a',
  40: '#641a21',
  50: '#7b1b27',
  60: '#931e2e',
  70: '#a91832',
  80: '#ca1f3d',
  90: '#e7334d',
  100: '#ff5666',
  110: '#ff737a',
  120: '#ff8a8d',
  130: '#ffa5a6',
  140: '#ffbfbf',
  150: '#ffd6d5',
  160: '#ffeded',
};
